apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector:
    app: helloworld
template:
  metadata:
    labels:
      app: helloworld
  spec:
    containers:
    - name: nodejs-demo
    image: syraxius/nodejs-test:0.0.1
    ports:
    - containerPort: 3000
